### PR TITLE
Linear pnp with eafe

### PR DESCRIPTION
**Pull request by arthbous**
This branch is not ready to merge.

I wrote lin_pnp_EAFE. 

The error with EAFE is
* cation l2 error is:     8.581501e-02
* anion l2 error is:      5.273684e-02
* potential l2 error is:  2.114196e-02

the error without EAFE is
* cation l2 error is:     8.244215e-06
* anion l2 error is:      5.480145e-06
* potential l2 error is:  5.858716e-06

So there is a problem...

### CODE REVIEW

**Comment by arthbous** [comment]
I added the L2Error in the Benchmarks/linear_PNP/lin_pnp.cpp and lin_pnp_eafe.cpp

lin_pnp_eafe converges but lin_pnp does not once the mesh is very fine

**Comment by arthbous** [comment]
50*50*3 (EAFE) :
Compute the error
	cation l2 error is:     2.696295e-05
	anion l2 error is:      9.644499e-06
	potential l2 error is:  1.528068e-06

50*50*3 :
Compute the error
	cation l2 error is:     1.054332e-16
	anion l2 error is:      3.141473e-17
	potential l2 error is:  9.946974e-17
	
80*80*3 :
Compute the error
	cation l2 error is:     1.016039e-13
	anion l2 error is:      3.500634e-14
	potential l2 error is:  1.413874e-13

80*80*3 (EAFE) :
Compute the error
	cation l2 error is:     5.882360e-06
	anion l2 error is:      1.634232e-06
	potential l2 error is:  2.332431e-07

100*100*5 (EAFE):
Compute the error
	cation l2 error is:     1.948317e-06
	anion l2 error is:      6.252527e-07
	potential l2 error is:  9.562431e-08

100*100*5
Compute the error
	cation l2 error is:     9.795974e-15
	anion l2 error is:      2.013015e-15
	potential l2 error is:  1.100591e-14

**Comment by arthbous** [comment]
This branch is still ready to get merged, we have to merged the feature/fasp_solver first

**Comment by arthbous** [comment]
Just merged master into it no more conflict

**Comment by maximilianmetti** [comment]
the benchmarks/linear_PNP/lin_PNP_EAFE.cpp and lin_pnp_eafe.cpp unit tests have no eafe in them...

**Comment by arthbous** [comment]
benchmarks/linear_PNP/lin_pnp_EAFE.cpp has EAFE lines 145 to 158 and lines 240-251

**Comment by arthbous** [comment]
The unit test is not done, I only worked on the benchmarks

**Comment by maximilianmetti** [comment]
Okay, do you want to make the unit test for this? This would be a good test to make sure EAFE works properly. I think this should be merged before the regular PNP.

**Comment by arthbous** [comment]
Unit tests done, I switch all the errors from l2 to the real L2. Good to merge

**Pull request merged**
