### PR TITLE
setup, solve, and test the linearized pnp solver

### PR DESCRIPTION
**Pull request by maximilianmetti**
@arthbous 
I spent some time putting together a new benchmark/ script.  The code has been re-organized to imitate the Newton solver format.

You don't have to merge this, I just wanted to show you what I had in mind for this linearized PNP benchmark.  Here's what I did:
- modified the .ufl file so that the analytic solution is known (and given as analytic expressions in lin_pnp.cpp).
- added boundary conditions
- used FEniCS to get the DoFs: ``get_dofs`` in fasp_to_fenics.cpp.  Your implementation assumed that the DoFs follow an interlacing pattern, which I'm not convinced is generally true (I'm thinking about adaptive meshing and so on).
- Computed initial guesses that satisfy the boundary conditions, so that we only solve for an update to the initial guess; this is a best practice for computing finite element solutions, and is absolutely necessary for Newton's method.
- added update functionality on a component-by-component basis (this is important for interfacing with the FASP solver for PNP).  This is in ``copy_dvector_to_vector_function`` in fasp_to_fenics.cpp

I think the code in benchmarks/linear_PNP/lin_PNP.cpp is pretty readable, so take a look and let me know what you think.
Here's what needs to be done:
- write a ``EigenMatrix_to_bdcsrMat`` function for block matrices
- find bug that gives a trivial update after solve.  This is either a mapping issue or a solving issue.  I'll figure this out over the weekend.

**This does not test EAFE.** We should test that *separately* since we should only update the code little-by-little to ensure nothing breaks.

### CODE REVIEW

**Comment by arthbous** [comment]
* the get_dofs function gives you the DoF of each sub component, I do not see how it is going to help in order to add EAFE matrix to the big matrix.
* If after a refinement you recompute the Function Space my method should be fine

Right now I focusing more on how to incorporate the EAFE in the PNP.

**Comment by arthbous** [comment]
Also, instead of the get_dof, I think you could do:

copy_dvector_to_vector_function(&solu_fasp, &solutionUpdate);
cation = solutionUpdate[0];
anion = solutionUpdate[1];
phi = solutionUpdate[2];

**Comment by maximilianmetti** [comment]
@arthbous 
I think this branch should be merged into master.  The benchmark is updated and there is a unit test to show that we solve the linearized equation to a desired accuracy.

**Comment by maximilianmetti** [comment]
I'm closing this PR to reset the base branch to master

**Pull request closed without merging**
