### PR TITLE
hotfix for tests to check decrease in relative residual

### PR DESCRIPTION
**Pull request by maximilianmetti**
Please review and merge.  I also changed the benchmarks

### CODE REVIEW

**Comment by maximilianmetti** [comment]
ping @arthbous

**Comment by arthbous** [comment]
Wouldn't that create conflicts with feature/newton-backtracking since these files are also modified in that branch ?

**Comment by maximilianmetti** [comment]
not if you merge now and then I resolve conflicts ; )

**Comment by arthbous** [comment]
I fixed the conflict. Check it out and merge

**Comment by maximilianmetti** [comment]
If it passes the unit tests, you can merge it.

**Pull request merged**
