### PR TITLE
init of the branch feature

### PR DESCRIPTION
**Pull request by arthbous**
Ok starting the assemble matrix for n species.

Just one problems is our files right now are for qn, qp,... we will have to change that also.

### CODE REVIEW

**Comment by arthbous** [comment]
**REMARKS**
* would it be possible to do ``q = 1.0   -1.0   1.0`` instead of qp= and then below qn = ?

* Also the combine of the matrix will work only for BSRmatrix. If we try to do CSR matrix the combining is going to be really hard.

* The combining also only works when everything is on the same space V. When we add stokes, it will have different vector space since it uses RT, do we add it to the matrix or it will be in a different one ?

PING @maximilianmetti

**Comment by maximilianmetti** [comment]
I think we should strive to make the coefficients get processed from a file like:
```
%--------------------------%
% PDE coefficients         %
%--------------------------%
% For dimensional analysis, it is critical
% that the coefficients are input in the
% correct units!
%
% Please, make sure to do so...

% Setup global variables
bc_coordinate         =  0              % 0 for x[0], 1 for x[1], 2 for x[2]
ref_voltage           =  1.0000e+0      % V
ref_density           =  1.0000e+0      % 1 / m^3
                                                         % use negative to measure in mM = mol / m^3
temperature           =  1.0000e+0      % K
relative_permittivity =  1.0000e-4      % no units
potential_upper_val   =  1.0000e+0      % ref_voltage * V
potential_lower_val   = -1.0000e+0      % ref_voltage * V


% first charge species
upper_concentration_val = 1.0000e-0   % ref_density
lower_concentration_val = 1.0000e-0   % ref_density
diffusivity    =  1.0000e-0      % m / sec^2
mobility       =  1.0000e-0      % (e_c/k_B*T) * m / sec^2
valency        =  1.0000e+0      % e_c

% second charge species
upper_concentration_val = 1.0000e-1   % ref_density
lower_concentration_val = 1.0000e-2   % ref_density
diffusivity     =  1.0000e-0      % m / sec^2
mobility        =  1.0000e-0      % (e_c/k_B*T) * m / sec^2
valency         = 2.0000e+0      % e_c

% third charge species
upper_concentration_val = 1.2000e-0   % ref_density
lower_concentration_val = 1.0200e-0   % ref_density
diffusivity     =  1.0000e-0      % m / sec^2
mobility        =  1.0000e-0      % (e_c/k_B*T) * m / sec^2
valency         = -1.0000e+0      % e_c
```
The properties would just get stored in an array so that they must be given in the appropriate order.

**Comment by maximilianmetti** [comment]
BSR is block, right?  that's the one we want to add/replace to anyway : )

**Comment by maximilianmetti** [comment]
is this still alive?

**Comment by arthbous** [comment]
Yes, except it copy it...

**Pull request closed without merging**
