### PR TITLE
Pnp with eafe

### PR DESCRIPTION
**Pull request by arthbous**
Everything is coded. See benchmarks/PNP/ except the test case I wrote does not converges

### CODE REVIEW

**Comment by arthbous** [comment]
It converges now, but the mesh needs to be very fine. Need to implement the mesh refinement with phi

**Comment by maximilianmetti** [comment]
Cation = 0 or anion = 0 is no physical. Density must be positive. You also need Dirichlet biundary conditions somewhere or else there will be trouble since the solution is defined only up to an arbitrary additive constant.

**Comment by arthbous** [comment]
Sorry I meant when I remove the analytic solution L_pnp.anion=L_pnp.cation=L_pnp.potential=0.
In this case it should be a physical test.

I had to create a new test by removing these lines from the ufl and I tried your test that you texted me
x=-1: anion=1, cation=0.1 potential=1
x=1: anion=0.1, cation=1 potential=-1
It converges easily with Epsilon=0.1 but not with epsilon=0.1

**Comment by maximilianmetti** [comment]
I don't know what the difference between Epsilon and epsilon is. But the RHS (L linear form) should simply be the negative of the nonlinear residual. I wouldn't base is off the linearized pnp ufl file.

**Comment by arthbous** [comment]
The RHS is right, I changed the ufl file from your linearized one. And Epslion=epsilon= the relative permittivity

**Comment by arthbous** [comment]
It converges now, my newton's used to not converge because of my initial guess.
It does takes twice as many iteration to converge with Epsilon=0.1 than with Epsilon=1

**Comment by maximilianmetti** [comment]
epsilon determines the convexity of the energy.  The bigger epsilon, the greater the convexity; the faster Newton converges.  That's a good sign.  The convergence is twice now only because the initial guess is close to the solution.  Once the solution is more complex, the two should be off by a smaller factor (hopefully).

**Comment by maximilianmetti** [comment]
the unit test doesn't do anything with EAFE...

**Comment by arthbous** [comment]
I changed the files. 

pnp and pnp_eafe do no converge with the exact solution

pnp_eafe2 converges, but very slowly. BSR convertion takes a lot of time.

you can just make pnp/pnp_eafe/pnp_eafe2 and run them

**Comment by arthbous** [comment]
I forgot to say
pnp and pnp_eafe solve nonlinear PNP with exact solutions in the source term
pnp_eafe2 is just the quick test with cation is 1 to 0.1 and anion 0.1 to 1 and phi 1 to -1.

**Comment by arthbous** [comment]
All good! Test it and merge it!

**Comment by maximilianmetti** [comment]
Did you resolve conflicts with master?

**Comment by arthbous** [comment]
No the merge master does not work...

**Comment by maximilianmetti** [comment]
Cannot auto resolve? Maybe to do with the change to reading in the domain parameters.

**Comment by arthbous** [comment]
Now it is. Git is so annoying...

**Pull request merged**
