### PR TITLE
Battery with stokes

### PR DESCRIPTION
**Pull request by arthbous**

### CODE REVIEW

**Comment by maximilianmetti** [comment]
this code doesn't compile...

**Comment by arthbous** [comment]
no it's missing Gauss Seildel

**Comment by maximilianmetti** [comment]
do you have any updates to commit to this branch?  Is battery-stokes.cpp working yet (except the linear solver part)?

**Comment by arthbous** [comment]
All done. Just need initial conditions to test it.

**Comment by arthbous** [comment]
No seg fault anymore. But the stokes solver is not doing anything..

**Comment by maximilianmetti** [comment]
why the ns solver takes a while:
screen shot 2016-02-16 at 10 24 36 pm

**Comment by XiaozheHu** [comment]
Hi Maxx,

Coarsening failed…  So basically one level method is used which could be really slow… 

Best
Xiaozhe

**Comment by maximilianmetti** [comment]
@XiaozheHu I see that.  I changed the solver to use Classic AMG with Aggressive coarsening and that shows improvement.  (The coarsening does not fail, but there is a warning:
```### WARNING: Coarsening might be too aggressive!```

**Comment by XiaozheHu** [comment]
Hi Maxx,

That is fine.  I am thinking the matrix we try to solve might have some issues.  Like it is very diagonal dominate, that is usually the reason why you get very aggressive coarsening.   

Best
Xiaozhe

**Pull request closed without merging**
