### PR TITLE
Feature/diode current

### PR DESCRIPTION
**Pull request by maximilianmetti**
Add a benchmark for computing current voltage relations for a semiconductor diode.

### CODE REVIEW

**Comment by maximilianmetti** [comment]
@arthbous Can you checkout this branch and run the diode benchmark?
```
cmake . && make pnp_diode && ./pnp_diode
```
I get a seg-fault at some point. I'd be curious to hear if you get the same thing. It has to run for quite a while before it has the seg-fault (maybe adjust the `max_newton` parameter in  `benchmarks/pnp_diode/main.cpp` to be about 30 to make it break faster. It takes a while to crash; so maybe run it before going to bed.

**Comment by arthbous** [comment]
I can but do I need EAFE ?

**Comment by maximilianmetti** [comment]
I'm using EAFE, although I'm not sure how much it's helping...

**Comment by maximilianmetti** [comment]
@arthbous I was able to successfully compute the IV curve for the diode; however, the mesh refinement strategy seems to be somewhat arbitrary. I'm using the entropy within each cell to determine when the refinement is sufficient, rather than computing the entropy and verifying that it is bounded.

That is getting dragged into this PR unfortunately. The current refinement strategy seems to target the appropriate regions, but it can be improved.  (The new update will require setting the entropy bound in physical units, which is a plus.)

**Pull request merged**
