### PR TITLE
Hotfix/periodic solution update 2

### PR DESCRIPTION
**Pull request by arthbous**
So, have you checked if you have the same error with this mesh ?

### CODE REVIEW

**Comment by arthbous** [comment]
@maximilianmetti

**Comment by maximilianmetti** [comment]
seems to work, but the solution is not periodic...  Is it so important that the solution is periodic or is this just some modeling assumption that we're imposing?  Maybe we should ask whether it is good enough to solve a Neumann problem?

**Comment by arthbous** [comment]
How do you see it's not periodic ? When I look in paraview it's hard for me to see any difference

**Comment by arthbous** [comment]
I changed the periodic boundary conditions, now it should be fixed

**Comment by maximilianmetti** [comment]
did you push? i only see a change in the binary file

**Comment by arthbous** [comment]
Omg I pushed the bin files....shame on me.
Now I pushed the cpp file

**Comment by maximilianmetti** [comment]
The code looks better, but when I plot the solution, it still isn't periodic at all...

**Comment by arthbous** [comment]
Now I can see that it's not "periodic". 

I have ideas:
1) It's actually periodic the difference of 0.01 between the values comes from some numeric approx..
2) the mesh is periodic on the boundary because of the spheres..
3) the periodic boundary do work with vector spaces...

**Comment by arthbous** [comment]
And the answer is...the mesh is NOT periodic...

**Comment by maximilianmetti** [comment]
I would be pretty surprised if the mesh was required to be periodic... I don't see why they wouldn't interpolate/use projection to get values for the slave DoFs

**Comment by arthbous** [comment]
On a old doc it says

> The implementation is based on matching degrees of freedom on G with degrees of freedom on H and only works when the mapping F is bijective between the sets of coordinates associated with the two domains. In other words, the nodes (degrees of freedom) must be aligned on G and H.

But since they are not align and we have very few points on the boundary it is normal that we have those difference of 0.1 in Phi, since it interpolates.
So I think we are all good.

**Comment by maximilianmetti** [comment]
I see a difference that is much greater than 0.1.  This difference looks greater than 12.
We're looking at potential.pvd at iteration 12.  (I hit the 'rescale to visible range' while looking at the face on the +z axis and then looked at the +x and -x faces.)  

Let me know if you see the same thing.

screen shot 2016-04-28 at 10 45 01 am
screen shot 2016-04-28 at 10 45 08 am

**Comment by arthbous** [comment]
How is that a difference of 12. it's from -6.37 to -6.04 ?

**Comment by maximilianmetti** [comment]
crap, you're right! It's a difference of 0.5 though.  If you look at it though, there's no way that the +x and -x faces are interpolated from one another; they're not even similar.

**Comment by arthbous** [comment]
Here is what I found,

>For periodic meshes, the points must match up exactly. 
When you use the CGAL mesh generator, this does not happen, whereas with the
built-in BoxMesh, the points are on a regular grid, so they do.
You need to build your mesh with a generator which can constrain the points on the boundaries.

So we need to match the mesh but we can't because we have those spheres...

**Comment by arthbous** [comment]
Idea for periodic, we don't do periodic but after each Newton iteration we interpolate the value of the opposite face to the the other face.

**Comment by maximilianmetti** [comment]
or, we could create a mass matrix and rip out the corresponding row for each master DoF and place it in the row for the slave DoF and put a -1 on the diagonal of that row.  That hack in interpolation.

**Comment by arthbous** [comment]
This would be hard, it would change the structure of the sparse matrix.

**Comment by maximilianmetti** [comment]
that's true, but periodicity also changes the structure of the matrix

**Comment by arthbous** [comment]
Yes but it's done before creating the matrix. it's done in the function space.
Adding value to a sparse matrix is hard...

**Pull request closed without merging**
