### PR TITLE
Develop doxygen

### PR DESCRIPTION
**Pull request by arthbous**
Added doxygen.

You just need to install doxygen and then `cmake . && make doc` and then look at `doc/html/index.html`

### CODE REVIEW

**Comment by arthbous** [comment]
@maximilianmetti , so what do you think of doxygen ? Is it good enough? Should I finish commenting everything ?

**Comment by maximilianmetti** [comment]
well... it certainly generates documentation...

I'm not sure how to navigate it that easily though. Maybe we need to teach it how to generate good docs.  The CSS file should be updated to make things look nice, and maybe there's another style for linking the index to functions?

**Comment by maximilianmetti** [comment]
It looks messy, but I think that's due to the poor structuring of the code from before...

Should we try moving all the old stuff into an ``archive/`` directory that is outside the ``doxygen`` scope and regenerate the docs? That should clean things up.  Unfortunately, it looks like it's documenting some ``doflin`` stuff too.

**Comment by arthbous** [comment]
It's the same thing that FASP is using, to see a full doc you can look at FASP documentations. I don't think it can be a lot better that than, the CSS is already modified to not look as ugly as the default theme. I fee like the way doxygen works is just to make a html version of all the .h files...

**Comment by arthbous** [comment]
I think you should remove all the other benchmkars from develop and yes it ass dolfin::Expression in the doc.

**Comment by maximilianmetti** [comment]
It might be documenting ``dolfin::Expression`` and ``dolfin::SubDomain`` because we declare subclasses to those classes... It might automatically bubble the documentation up to cover *all* parent classes. 

Oh well, that's not so bad : )

**Comment by maximilianmetti** [comment]
Can you figure out how to exclude some patterns?  I'm able to exclude files from the ``tests/`` directory; but, I'd like to exclude all files with ``*_forms.h``, since that is how I identify header files generated from ``.ufl`` files.

**Comment by arthbous** [comment]
You mean doxyfile.in ? not doxyfile

**Comment by maximilianmetti** [comment]
I just did it in the Doxyfile... not the Doxyfile.in

**Comment by arthbous** [comment]
It should be in the Doxfile.in because the Doxyfile is rewritten when you do cmake .

**Comment by maximilianmetti** [comment]
That didn't work either.

**Comment by arthbous** [comment]
You have to add:

`XCLUDE_PATTERNS = @PROJECT_SOURCE_DIR@/tests/* \
		   *_forms.*`

to Doxyfile.in and it works. I pushed it.

**Comment by maximilianmetti** [comment]
so... why doesn't it document the ``poisson.h`` header file in ``benchmark/poisson``?

**Comment by arthbous** [comment]
That's a good question and my answer is that Doxygen is horrible...

**Pull request closed without merging**
