### PR TITLE
fixes a bug that properly updates residual to incorporate periodic

### PR DESCRIPTION
**Pull request by maximilianmetti**
Also removes use of uninitialized variables in funcspace_to_vecspace::replace_row

### CODE REVIEW

**Comment by arthbous** [comment]
Nice!

Have you tried using EAFE ? Because when I used it, it does not converges.

**Comment by maximilianmetti** [comment]
it does not converge as quickly and gets stuck; this might be related to poor mesh quality.  Then there's the issue that phi gets screwed up after some adaptivity.  It's average value jumps greatly (roughly by an additive constant of 8) everywhere except the fixed point.

We have to figure out what causes that...

**Comment by arthbous** [comment]
So the mesh does something to the Bernoulli thingy ?

And Yes every time the mesh is adapted it explodes

**Comment by maximilianmetti** [comment]
Well, since EAFE isn't applied to the sub-matrix for phi, I don't see how the periodic BC would be interacting with EAFE.  That leads me to think it's something with the mesh.

We need to figure out why phi gets screwed up after some adapts... can you take a look?

**Comment by arthbous** [comment]
I finished the tests and Phi is fine after some adapts. So adapting mesh is fine.

The only problem is really just EAFE.

**Comment by maximilianmetti** [comment]
It happens without EAFE too.  Run the solver until t=3 and you'll get an issue.  It just happens sooner with EAFE for some reason.

**Comment by arthbous** [comment]
Just tried and it works, the only issue I get is if you refine like 20 times

**Comment by maximilianmetti** [comment]
what causes the issue though.  That's the important question here.

**Comment by arthbous** [comment]
Ok I was able to recreate the issue. I did just one sphere to make it easier, and let's say I start with 10 cells in my mesh then the refinement does not work. Now if I start with 20 cells then the refinement works. The shape of the initial mesh seems to be very important.

Then I tried with EAFE and it still does not work. My guess there is an issue with EAFE and the spheres.

Also, I think the problem is that the refinement seems to only happen around the spheres, which is not necessarily where we want to refine. Should we add the DirichletBC = 0 on the spheres ?

**Comment by maximilianmetti** [comment]
phi is getting screwed up for some reason... We have to figure out the specific cause of that before we start trying to hack our way out of this.

It makes sense that the refinement happens on the spheres too; that's where the boundary layers (and *all* the interesting behavior) is going on!

**Pull request closed without merging**
